# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/multisecret_simple_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_multisecret_gui(object):
    def setupUi(self, multisecret_gui):
        multisecret_gui.setObjectName("multisecret_gui")
        multisecret_gui.resize(733, 468)
        self.tabWidget = QtWidgets.QTabWidget(multisecret_gui)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 751, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 711, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.button_split = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_split.setObjectName("button_split")
        self.gridLayout.addWidget(self.button_split, 4, 4, 1, 1)
        self.check_s2p1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s2p1.setObjectName("check_s2p1")
        self.gridLayout.addWidget(self.check_s2p1, 2, 5, 1, 1)
        self.secret_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secret_1.setObjectName("secret_1")
        self.gridLayout.addWidget(self.secret_1, 0, 4, 1, 1)
        self.label_secret2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_secret2.setObjectName("label_secret2")
        self.gridLayout.addWidget(self.label_secret2, 2, 0, 1, 1)
        self.prime = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.prime.setObjectName("prime")
        self.gridLayout.addWidget(self.prime, 5, 4, 1, 1)
        self.check_s3p2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s3p2.setObjectName("check_s3p2")
        self.gridLayout.addWidget(self.check_s3p2, 3, 6, 1, 1)
        self.label_secret3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_secret3.setObjectName("label_secret3")
        self.gridLayout.addWidget(self.label_secret3, 3, 0, 1, 1)
        self.check_s1p2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s1p2.setObjectName("check_s1p2")
        self.gridLayout.addWidget(self.check_s1p2, 0, 6, 1, 1)
        self.check_s1p1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s1p1.setObjectName("check_s1p1")
        self.gridLayout.addWidget(self.check_s1p1, 0, 5, 1, 1)
        self.secret_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secret_3.setObjectName("secret_3")
        self.gridLayout.addWidget(self.secret_3, 3, 4, 1, 1)
        self.check_s1p3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s1p3.setObjectName("check_s1p3")
        self.gridLayout.addWidget(self.check_s1p3, 0, 7, 1, 1)
        self.check_s3p1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s3p1.setObjectName("check_s3p1")
        self.gridLayout.addWidget(self.check_s3p1, 3, 5, 1, 1)
        self.label_prime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_prime.setObjectName("label_prime")
        self.gridLayout.addWidget(self.label_prime, 5, 0, 1, 1)
        self.secret_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secret_2.setObjectName("secret_2")
        self.gridLayout.addWidget(self.secret_2, 2, 4, 1, 1)
        self.check_s2p2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s2p2.setObjectName("check_s2p2")
        self.gridLayout.addWidget(self.check_s2p2, 2, 6, 1, 1)
        self.label_secret1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_secret1.setObjectName("label_secret1")
        self.gridLayout.addWidget(self.label_secret1, 0, 0, 1, 1)
        self.check_s2p3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s2p3.setObjectName("check_s2p3")
        self.gridLayout.addWidget(self.check_s2p3, 2, 7, 1, 1)
        self.check_s3p3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s3p3.setObjectName("check_s3p3")
        self.gridLayout.addWidget(self.check_s3p3, 3, 7, 1, 1)
        self.statusbar = QtWidgets.QLabel(self.tab)
        self.statusbar.setGeometry(QtCore.QRect(10, 417, 721, 20))
        self.statusbar.setObjectName("statusbar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 711, 391))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 6, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.button_combine = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_combine.setObjectName("button_combine")
        self.gridLayout_2.addWidget(self.button_combine, 6, 0, 1, 1)
        self.button_load_share_1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_load_share_1.setObjectName("button_load_share_1")
        self.gridLayout_2.addWidget(self.button_load_share_1, 0, 2, 1, 1)
        self.button_load_share_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_load_share_2.setObjectName("button_load_share_2")
        self.gridLayout_2.addWidget(self.button_load_share_2, 3, 2, 1, 1)
        self.button_load_share_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_load_share_3.setObjectName("button_load_share_3")
        self.gridLayout_2.addWidget(self.button_load_share_3, 4, 2, 1, 1)
        self._button_load_public_info = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self._button_load_public_info.setObjectName("_button_load_public_info")
        self.gridLayout_2.addWidget(self._button_load_public_info, 5, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 691, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.number_of_secrets = QtWidgets.QSpinBox(self.layoutWidget)
        self.number_of_secrets.setMinimum(2)
        self.number_of_secrets.setMaximum(97)
        self.number_of_secrets.setProperty("value", 3)
        self.number_of_secrets.setObjectName("number_of_secrets")
        self.gridLayout_3.addWidget(self.number_of_secrets, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.number_of_users = QtWidgets.QSpinBox(self.layoutWidget)
        self.number_of_users.setMinimum(2)
        self.number_of_users.setProperty("value", 3)
        self.number_of_users.setObjectName("number_of_users")
        self.gridLayout_3.addWidget(self.number_of_users, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.actionSetSecretsNumber = QtWidgets.QAction(multisecret_gui)
        self.actionSetSecretsNumber.setObjectName("actionSetSecretsNumber")

        self.retranslateUi(multisecret_gui)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(multisecret_gui)

    def retranslateUi(self, multisecret_gui):
        _translate = QtCore.QCoreApplication.translate
        multisecret_gui.setWindowTitle(_translate("multisecret_gui", "Multi-secret Sharing Tool"))
        self.button_split.setText(_translate("multisecret_gui", "Split secrets"))
        self.check_s2p1.setText(_translate("multisecret_gui", "User 1"))
        self.label_secret2.setText(_translate("multisecret_gui", "Secret 2"))
        self.check_s3p2.setText(_translate("multisecret_gui", "User 2"))
        self.label_secret3.setText(_translate("multisecret_gui", "Secret 3"))
        self.check_s1p2.setText(_translate("multisecret_gui", "User 2"))
        self.check_s1p1.setText(_translate("multisecret_gui", "User 1"))
        self.check_s1p3.setText(_translate("multisecret_gui", "User 3"))
        self.check_s3p1.setText(_translate("multisecret_gui", "User 1"))
        self.label_prime.setText(_translate("multisecret_gui", "Prime"))
        self.check_s2p2.setText(_translate("multisecret_gui", "User 2"))
        self.label_secret1.setText(_translate("multisecret_gui", "Secret 1"))
        self.check_s2p3.setText(_translate("multisecret_gui", "User 3"))
        self.check_s3p3.setText(_translate("multisecret_gui", "User 3"))
        self.statusbar.setText(_translate("multisecret_gui", "Status Bar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("multisecret_gui", "Roy-Adhikari split"))
        self.label_4.setText(_translate("multisecret_gui", "User 2"))
        self.label_8.setText(_translate("multisecret_gui", "User 1"))
        self.label_6.setText(_translate("multisecret_gui", "Load public information"))
        self.button_combine.setText(_translate("multisecret_gui", "Combine secrets"))
        self.button_load_share_1.setText(_translate("multisecret_gui", "Load pseudo share..."))
        self.button_load_share_2.setText(_translate("multisecret_gui", "Load pseudo share..."))
        self.button_load_share_3.setText(_translate("multisecret_gui", "Load pseudo share..."))
        self._button_load_public_info.setText(_translate("multisecret_gui", "Load public information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("multisecret_gui", "Combine secret from file"))
        self.label.setText(_translate("multisecret_gui", "Number of secrets"))
        self.label_2.setText(_translate("multisecret_gui", "Number of users"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("multisecret_gui", "Problem size"))
        self.actionSetSecretsNumber.setText(_translate("multisecret_gui", "setSecretsNumber"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    multisecret_gui = QtWidgets.QDialog()
    ui = Ui_multisecret_gui()
    ui.setupUi(multisecret_gui)
    multisecret_gui.show()
    sys.exit(app.exec_())

