# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multisecret_simple_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_scada_gui(object):
    def setupUi(self, scada_gui):
        scada_gui.setObjectName("scada_gui")
        scada_gui.resize(733, 468)
        self.tabWidget = QtWidgets.QTabWidget(scada_gui)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 751, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 711, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.button_split = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_split.setObjectName("button_split")
        self.gridLayout.addWidget(self.button_split, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.check_s2p1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s2p1.setObjectName("check_s2p1")
        self.gridLayout.addWidget(self.check_s2p1, 3, 2, 1, 1)
        self.secret_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secret_1.setObjectName("secret_1")
        self.gridLayout.addWidget(self.secret_1, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.prime = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.prime.setObjectName("prime")
        self.gridLayout.addWidget(self.prime, 6, 1, 1, 1)
        self.check_s3p2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s3p2.setObjectName("check_s3p2")
        self.gridLayout.addWidget(self.check_s3p2, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.check_s1p2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s1p2.setObjectName("check_s1p2")
        self.gridLayout.addWidget(self.check_s1p2, 1, 3, 1, 1)
        self.check_s1p1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s1p1.setObjectName("check_s1p1")
        self.gridLayout.addWidget(self.check_s1p1, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.check_s1p3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s1p3.setObjectName("check_s1p3")
        self.gridLayout.addWidget(self.check_s1p3, 1, 4, 1, 1)
        self.check_s3p1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s3p1.setObjectName("check_s3p1")
        self.gridLayout.addWidget(self.check_s3p1, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.secret_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secret_3.setObjectName("secret_3")
        self.gridLayout.addWidget(self.secret_3, 4, 1, 1, 1)
        self.check_s2p2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s2p2.setObjectName("check_s2p2")
        self.gridLayout.addWidget(self.check_s2p2, 3, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.check_s2p3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s2p3.setObjectName("check_s2p3")
        self.gridLayout.addWidget(self.check_s2p3, 3, 4, 1, 1)
        self.check_s3p3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_s3p3.setObjectName("check_s3p3")
        self.gridLayout.addWidget(self.check_s3p3, 4, 4, 1, 1)
        self.secret_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secret_2.setObjectName("secret_2")
        self.gridLayout.addWidget(self.secret_2, 3, 1, 1, 1)
        self.statusbar = QtWidgets.QLabel(self.tab)
        self.statusbar.setGeometry(QtCore.QRect(10, 417, 721, 20))
        self.statusbar.setObjectName("statusbar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(scada_gui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(scada_gui)

    def retranslateUi(self, scada_gui):
        _translate = QtCore.QCoreApplication.translate
        scada_gui.setWindowTitle(_translate("scada_gui", "Dialog"))
        self.button_split.setText(_translate("scada_gui", "Split secrets"))
        self.label_6.setText(_translate("scada_gui", "User 2"))
        self.check_s2p1.setText(_translate("scada_gui", "CheckBox"))
        self.label_2.setText(_translate("scada_gui", "Secret 2"))
        self.check_s3p2.setText(_translate("scada_gui", "CheckBox"))
        self.label_3.setText(_translate("scada_gui", "Secret 3"))
        self.check_s1p2.setText(_translate("scada_gui", "CheckBox"))
        self.check_s1p1.setText(_translate("scada_gui", "CheckBox"))
        self.label_7.setText(_translate("scada_gui", "User 3"))
        self.check_s1p3.setText(_translate("scada_gui", "CheckBox"))
        self.check_s3p1.setText(_translate("scada_gui", "CheckBox"))
        self.label_5.setText(_translate("scada_gui", "Prime"))
        self.check_s2p2.setText(_translate("scada_gui", "CheckBox"))
        self.label.setText(_translate("scada_gui", "Secret 1"))
        self.label_4.setText(_translate("scada_gui", "User 1"))
        self.check_s2p3.setText(_translate("scada_gui", "CheckBox"))
        self.check_s3p3.setText(_translate("scada_gui", "CheckBox"))
        self.statusbar.setText(_translate("scada_gui", "Status Bar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("scada_gui", "Roy-Adhikari"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("scada_gui", "Multi-secret sharing algorithm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    scada_gui = QtWidgets.QDialog()
    ui = Ui_scada_gui()
    ui.setupUi(scada_gui)
    scada_gui.show()
    sys.exit(app.exec_())

